### ISSUE TITLE
question: do you plan to publish to BrickHub?

### ISSUE THREAD

**Issue by felangel** [yardexx/freerasp_brick#8]
Awesome job with this brick!

I’ll definitely be testing it out in the near future but wanted to see whether you planned to publish to https://brickhub.dev? 

Cheers!

**Comment by yardexx** [comment]
Hi @felangel, thanks for the question.

Since Mason is doing its job really well, **I plan to upload freerasp_brick to brickhub.dev soon** - after issue #6 is resolved because that is the most painful point of setup (and the main reason why this brick even exists).

Looking forward to it 💙
